In [2]:
import pandas as pd 

df = pd.read_csv('submission_v6.csv')
df

    id  TCC  MS  M  VC  VA  VE
0    0    1   2  2   3   3   1
1    1    1   1  2   1   3   2
2    2    1   2  2   2   3   1
3    3    2   2  2   1   3   1
4    4    2   2  2   1   3   2
..  ..  ...  .. ..  ..  ..  ..
57  57    1   0  2   3   3   2
58  58    1   1  2   3   3   2
59  59    1   2  2   2   1   2
60  60    1   1  2   3   3   1
61  61    1   1  2   3   3   2

[62 rows x 7 columns]

In [3]:
va_ve = pd.read_csv('output/submission_VC_video_test.csv')
va_ve

    id  TCC  MS  M  VC  VA  VE
0    0    0   0  0   1   0   0
1    1    0   0  0   2   0   0
2    2    0   0  0   2   0   0
3    3    0   0  0   1   0   0
4    4    0   0  0   1   0   0
..  ..  ...  .. ..  ..  ..  ..
57  57    0   0  0   1   0   0
58  58    0   0  0   3   0   0
59  59    0   0  0   2   0   0
60  60    0   0  0   2   0   0
61  61    0   0  0   2   0   0

[62 rows x 7 columns]

In [5]:
df['VC'] = va_ve['VC']
df

    id  TCC  MS  M  VC  VA  VE
0    0    1   2  2   1   3   1
1    1    1   1  2   2   3   2
2    2    1   2  2   2   3   1
3    3    2   2  2   1   3   1
4    4    2   2  2   1   3   2
..  ..  ...  .. ..  ..  ..  ..
57  57    1   0  2   1   3   2
58  58    1   1  2   3   3   2
59  59    1   2  2   2   1   2
60  60    1   1  2   2   3   1
61  61    1   1  2   2   3   2

[62 rows x 7 columns]

In [6]:
df.to_csv('submission_v7.csv', index=False)

# Version 8

In [1]:
import pandas as pd

df = pd.read_csv('submission_v7.csv')
df

    id  TCC  MS  M  VC  VA  VE
0    0    1   2  2   1   3   1
1    1    1   1  2   2   3   2
2    2    1   2  2   2   3   1
3    3    2   2  2   1   3   1
4    4    2   2  2   1   3   2
..  ..  ...  .. ..  ..  ..  ..
57  57    1   0  2   1   3   2
58  58    1   1  2   3   3   2
59  59    1   2  2   2   1   2
60  60    1   1  2   2   3   1
61  61    1   1  2   2   3   2

[62 rows x 7 columns]

In [2]:
va = pd.read_csv('output/submission_VA_video_test.csv')
va

    id  TCC  MS  M  VC  VA  VE
0    0    0   0  0   0   3   0
1    1    0   0  0   0   3   0
2    2    0   0  0   0   2   0
3    3    0   0  0   0   3   0
4    4    0   0  0   0   2   0
..  ..  ...  .. ..  ..  ..  ..
57  57    0   0  0   0   3   0
58  58    0   0  0   0   3   0
59  59    0   0  0   0   1   0
60  60    0   0  0   0   3   0
61  61    0   0  0   0   3   0

[62 rows x 7 columns]

In [3]:
df['VA'] = va['VA']
df

    id  TCC  MS  M  VC  VA  VE
0    0    1   2  2   1   3   1
1    1    1   1  2   2   3   2
2    2    1   2  2   2   2   1
3    3    2   2  2   1   3   1
4    4    2   2  2   1   2   2
..  ..  ...  .. ..  ..  ..  ..
57  57    1   0  2   1   3   2
58  58    1   1  2   3   3   2
59  59    1   2  2   2   1   2
60  60    1   1  2   2   3   1
61  61    1   1  2   2   3   2

[62 rows x 7 columns]

In [4]:
df.to_csv('submission_v8.csv', index=False)

# Version 9

In [1]:
import pandas as pd

df = pd.read_csv('submission.csv')
df

    id  TCC  MS  M  VC  VA  VE
0    0    1   1  2   0   0   0
1    1    1   1  2   0   0   0
2    2    1   2  2   0   0   0
3    3    2   2  2   0   0   0
4    4    2   2  2   0   0   0
..  ..  ...  .. ..  ..  ..  ..
57  57    1   0  2   0   0   0
58  58    1   1  2   0   0   0
59  59    1   1  2   0   0   0
60  60    1   1  2   0   0   0
61  61    1   1  2   0   0   0

[62 rows x 7 columns]

In [2]:
video = ['VC', 'VA', 'VE']
df_video = pd.read_csv('submission_v8.csv')
df[video] = df_video[video]
df

    id  TCC  MS  M  VC  VA  VE
0    0    1   1  2   1   3   1
1    1    1   1  2   2   3   2
2    2    1   2  2   2   2   1
3    3    2   2  2   1   3   1
4    4    2   2  2   1   2   2
..  ..  ...  .. ..  ..  ..  ..
57  57    1   0  2   1   3   2
58  58    1   1  2   3   3   2
59  59    1   1  2   2   1   2
60  60    1   1  2   2   3   1
61  61    1   1  2   2   3   2

[62 rows x 7 columns]

In [3]:
df.to_csv('submission_v9.csv', index=False)